### ISSUE TITLE
Rake jasmine doesn't work

### ISSUE THREAD

**Issue by dupuchba** [froots/backbone-jasmine-examples#5]
Hi all the command shows this error (see bellow)

```
rake jasmine
```

![capture decran 2013-05-19 a 14 44 37](https://f.cloud.github.com/assets/911705/522956/eeccc990-c081-11e2-924c-0394c58912e1.png)

I am not using rails for the backend (and I don't know anything about rails) and I am only here to train on Jasmine... anyone knows what I am facing?

Thx

**Comment by GengGao** [comment]
@dupuchba looks like you need to install json.
Add the following to Gemfile
 gem 'json'
 and do bundle update

hope this helps.
